Desenvolvimento da integração com Apache Kafka Consumer 2
diegolribeiro/projeto_kafka pull request #1
Opened 2020-01-21 01:16 UTC by diegolribeiro

2020-01-21 23:24 UTC, tiagokamegasawa approved these changes

2020-01-26 14:11 UTC, GoncalvesGabriel requested changes
Coloquei alguns comentários

2020-01-26 14:11 UTC, GoncalvesGabriel commented on consumidor-two/src/main/resources/docker/docker-compose.yml
> +version: '3.7'
Acho que falta acrescentar as outras imagens, a do producer e do outro consumer que está pronto. Fora que acho que precisa colocar o zookeeper

2020-01-27 12:53 UTC, diegolribeiro commented on consumidor-two/src/main/resources/docker/docker-compose.yml
> +version: '3.7'
Escolhi essa imagem do spotify pq já tem o zookeper junto com o kafka.

2020-02-03 00:07 UTC, merged